### ISSUE TITLE
failed installation

### ISSUE THREAD

**Issue by quyaingo** [duct317/scDHA#10]
Hello,

I could not install scDHA because the package clusterCrit is no longer in CRAN.

Thank you in advance for your help.

**Comment by duct317** [comment]
Hi,

Thank you for letting me know. I have submitted the new version without `clusterCrit` dependency to CRAN. It should be available in a few days.

In the meantime, you can use `devtools` to install `scDHA` from GitHub: `devtools::install_github('duct317/scDHA')`

Let me know if you still have problem installing `scDHA`.

**Comment by quyaingo** [comment]
It worked. Thanks a lot!
