### ISSUE TITLE
Encountering error "Error in { : task 1 failed - "task 1 failed - "subscript out of bounds"""

### ISSUE THREAD

**Issue by zyzisastudyreallyhardguy** [duct317/scDHA#13]
Dear scDHA authors,

Thank you for your great work! I want to use my own data to run scDHA, but encounter the following error. I have made sure the rows are cells and the columns are genes. Could you please help me with this issue?
<img width="580" alt="image" src="https://user-images.githubusercontent.com/75228223/230808186-82e6740b-1282-4196-a1cd-b6a05e96be04.png">
.

Thank you very much!

Best Regards,

**Comment by duct317** [comment]
Hi,

Thank you for your interest in scDHA and sorry for the late reply.

It's pretty hard to comment on what exactly is the problem without looking at the data. But I think you can try to scale your data using z-score or log transformation. Let me know if that would solve your problem.

Thank you.

**Comment by zyzisastudyreallyhardguy** [comment]
Thank you for your reply! I use a cell gene matrix with 1400+ cells and 20000+ genes. When I reduce the number of cells to 200, the error disappeared. 

I have applied the log transformation as you suggested. The algorithm still encounters errors when the number of cells is larger than 200.

Could you please help me with this issue?

Warmest Regards
