### ISSUE TITLE
Index 1 and Index 2

### ISSUE THREAD

**Issue by nottwy** [duct317/scDHA#3]
In your article, you give two formulas as following:

![2021-06-11_004435](https://user-images.githubusercontent.com/4936625/121564791-6bd03880-ca4e-11eb-95d5-f89aa0ead40d.png)

Could you give more description about:
1. between sum of squares
2. total sum of squares
3. within sum of squares

My question is: square of what?

**Comment by duct317** [comment]
Hi,

These are the metrics from k-means clustering, you can read about it here:
https://www.datanovia.com/en/lessons/k-means-clustering-in-r-algorith-and-practical-examples/

These are sums of square of distances:
1/ Sum of squares of distance from points in one cluster to centers of other clusters.
2/ Sum of all square of distances.
3/ Sum of squares of distances from points in one cluster to the centers of that cluster. 
So, 2 = 1 + 3
