### ISSUE TITLE
Is the memory-saving Voting Procedure implemented in this package?

### ISSUE THREAD

**Issue by EdwardAgboraw** [duct317/scDHA#4]
In the paper, a voting-procedure that applies the clustering algorithm on a subset of the data points is mentioned. Is this option possible using this package, and, if yes, how can it be accessed?

**Comment by duct317** [comment]
Hi, 
The voting procedure is already integrated in the package. You don't need to enable it by yourself. 
If the memory is a concern for you, you can convert the input matrix to a sparse matrix, and set the parameter `sparse=TRUE` for `scDHA` function. This would greatly reduce the memory usage. However, the sparse matrix must not have any negative value. Let me know if you have any problem using the feature.
