### ISSUE TITLE
How to organize input data from raw scRNA-seq data

### ISSUE THREAD

**Issue by scho392** [duct317/scDHA#7]
Hi. I am new to the scRNA-seq analysis, and I have exploring your program to perform analysis.
How can I generate input data like the example you provided, Goolam?
I used Seurat to combine matrix.mtx, barcodes.tsv, and features.tsv. 
I also have multiple analyses for the samples taken at different time point.
How can I combine those?

**Comment by duct317** [comment]
Hi,
To generate input similar to Goolam dataset, you can use the package SingleCellExperiment https://bioconductor.org/packages/release/bioc/html/SingleCellExperiment.html
However, if you want to perform analysis using scDHA, you only need a matrix with rows as samples and columns as genes. The matrix can be dense or sparse. If you use sparse matrix, you need to enable the `sparse` option for scDHA.

For data with different time points, I am not sure how to combine them. But the simplest way you can try would be concatenating all the matrices into one.

Let me know if you have other questions.
